### ISSUE TITLE
Collab notebook out of date

### ISSUE THREAD

**Issue by BobBorges** [swerik-project/the-swedish-parliament-corpus#2]
We link to a collab notebook in the readme, but it's out of date. There's already a notebook in pyriksdagen; do we need two notebooks?

either

- [ ] unlink collab

or

- [ ] update collab

**Comment by ninpnin** [comment]
I say unlink Colab, unless there's an easy way for it to automatically pull changes from github.

**Comment by ninpnin** [comment]
Nevermind, this seems to work!

https://colab.research.google.com/github/swerik-project/pyriksdagen/blob/main/examples/corpus-walkthrough.ipynb
