### ISSUE TITLE
Decide on how to store decisions

### ISSUE THREAD

**Issue by MansMeg** [swerik-project/the-swedish-parliament-corpus#5]
We need to decide how to store project-wide decisions in a good way. I wrote this down. We can the discussing in the TAB at the end of May.

https://docs.google.com/document/d/1laoqeVd2ZoWzjpWxbK1vcHdDUrd2FAliVTuJ3LrGBtU/edit?usp=sharing

**Comment by fredrik1984** [comment]
Thank you for setting up this document!

**Comment by BobBorges** [comment]
https://github.com/swerik-project/the-swedish-parliament-corpus/commit/b55804f8235503f8566915544d861baa090ce2ff
