### ISSUE TITLE
Point to the repositories at the landing page

### ISSUE THREAD

**Issue by MansMeg** [swerik-project/the-swedish-parliament-corpus#8]
We should point to the riksdagen-records and riksdagen-persons repos at the landing page.

**Comment by BobBorges** [comment]
Wasn't the idea to point to the released/zipped data on the landing page? There everything is easily findable in its most user-friendly format. Maybe point to the other repos under a "how to contribute" section or similar.

**Comment by MansMeg** [comment]
I think we should have both: a zip file for some users and a link to the repo for others more advanced. For some users (me included) the repos are more user-friendly.

**Comment by MansMeg** [comment]
We dont need anything big. Did a PR to show.

**Comment by BobBorges** [comment]
It's exactly what I would do, but you'll have to edit `readme/readme-template.md` if you want your changes to survive the next release.

**Comment by MansMeg** [comment]
Ok. Great. Will do. Now Im checking out.

**Comment by BobBorges** [comment]
https://github.com/swerik-project/the-swedish-parliament-corpus/commit/ea469b3d4028953540e071749ea6c42167937803
